const data = [
  {
    picture: '/img/mark.png',
    name: 'Mark Webber',
    action: 'reacted to your recent post',
    link: 'My first tournament today!',
    date: '1m ago',
    read: false,
    id: 1,
  },
  {
    picture: '/img/angela.png',
    name: 'Angela Gray',
    action: 'followed you',
    date: '5m ago',
    read: false,
    id: 2,
  },
  {
    picture: '/img/jacob.png',
    name: 'Jacob Thompson',
    action: 'has joined your group',
    link: 'Chess Club',
    date: '1 day ago',
    read: false,
    id: 3,
  },
  {
    picture: '/img/rizky.png',
    name: 'Rizky Hasanuddin',
    action: 'sent you a private message',
    child:
      'Hello, thanks for setting up the Chess Club. I’ve been a member for a few weeks now and I’m already having lots of fun and improving my game.',
    date: '5 days ago',
    read: false,
    id: 4,
  },
  {
    picture: '/img/kimberly.png',
    name: 'Kimberly Smith',
    action: 'commented on your picture',
    profilePic: '/img/profilepic.png',
    date: '1 week ago',
    read: true,
    id: 5,
  },
  {
    picture: '/img/nathan.png',
    name: 'Nathan Peterson',
    action: 'reacted to your recent post',
    link: '5 end-game strategies to increase your win rate',
    date: '2 weeks ago',
    read: true,
    id: 6,
  },
  {
    picture: '/img/anna.png',
    name: 'Anna Kim',
    action: 'left the group',
    link: 'Chess Club',
    date: '2 weeks ago',
    read: true,
    id: 7,
  },
];

export default data;
